const {Given, When, Then} = require("@cucumber/cucumber");
const addProspectActions = require('../support/addProspectActions');
const Utils = require('../support/utils');
const subscriberlistActions = require('../support/subscriberlistActions');


When(/^I go to add prospect interface to create a prospect$/, function() {
	addProspectActions.clickGlobalCreateMenu();
	addProspectActions.clickAddProspectOption();
});


When(/^I fill the required details$/, () => {
	addProspectActions.fillRequiredDetailsSubscriber ();   
	addProspectActions.clickNextButton();   
});

// // this could disabled
// When(/^I make sure that 'Account auto-genration' option is enabled$/, () => {
// 	addProspectActions.accountAutoGenerationEnabled();
// });


When(/^I make sure that 'Account auto-generation' option is (.*)$/, function(status)  {
	addProspectActions.accountAutoGenerationEnabled(status);    
	
});


When(/^I provide username and password$/, () => {
	addProspectActions.enterUsernameAndPassword();
});


When(/^I save the record$/, () => {
	addProspectActions.saveNewSubscriber();
   	addProspectActions.verificationMsgForNewSubscriberAdded ();
});

When(/^I ensure that default default Grace Period settings are applied in settings$/,function() {
	addProspectActions.ensureGracePeriodSettingsApplied();
});	
When(/^I ensure default Auto Action settings are applied in settings$/,function() {
	addProspectActions.ensureAutoActionSettingsApplied();
});


Then(/^I verify that the new prospect or subscriber is added in subscriber list$/, () => {
	addProspectActions.closeNewlyAddedProspect();
	subscriberlistActions.openSubscriberList();
	//subscriberlistActions.clickSortingButton("All");
	//subscriberlistActions.clickSortingButton("Prospect");
	addProspectActions.verifyProspectAdded();
	
});


Then(/^I should see that username and password are autogenerated$/, () => {
 	addProspectActions.verifyNewlyAddedSubscriberOpens();
    addProspectActions.validateRandomUsernameAndPassword();

 });

 
Then(/^I should see that username and password are same on username popup on subscriber details drawer$/, () => {
    addProspectActions.verifyNewlyAddedSubscriberOpens();
    addProspectActions.validateSetUsernameAndPassword();
});



Then(/^The newly added prospect is added successfully$/, () => {
	addProspectActions.verifyNewlyAddedSubscriberOpens();
});


Then(/^The Subscriber dock is automatically opened for the new subscriber with accurate contact info$/, () => {
    addProspectActions.verifyNewlyAddedSubscriberOpens();
});


Then(/^I can view in the Billing Status section that the default billing days settings are correctly applied to the new subscriber$/, () => {
	addProspectActions.checkInvoiceSettingforBilling();
    addProspectActions.openBillingOptionTab();
	addProspectActions.verifyBillingSettingsForSubscriber();

});


Then(/^I should see the Add prospect or subscriber interface$/, function()  {
	addProspectActions.verifyAddProspectInterfaceOpened();
});


Then(/^I should see Primary Contact, Billing Contact, and Contact Emails sections in the Add Prospect or Subscriber panel$/, () => {
	addProspectActions.sectionsAreVisibleOnProspectPanel();
});


Then(/^I can see the default cycle of prospect as monthly$/, () => {
    addProspectActions.openBillingOptionTab();
    addProspectActions.verifyDefaultTaxCycleAsMonthly();
});


Then(/^I can view in the Billing Options section that the default tax setting is set correctly based on the new subscriber's billing info and the tax criteria$/, () => {
    addProspectActions.openBillingOptionTab();
    addProspectActions.openTaxDropdown();
    addProspectActions.applyTaxProfileFromDropdown();
});


Then(/^I fill the required details and save$/,function() {
	addProspectActions.fillProspectForm('fullActionPerform');
	Utils.clearLocalStorage()
});
Then(/^A new prospect or subscriber should be added$/,function() {
	addProspectActions.verifyProspectusAdd();
	Utils.clearLocalStorage()
});
Then(/^I can view that the Paper Invoice option is unchecked by default$/,function() {
	addProspectActions.verifyPaperInvoiceUnchecked();
	Utils.clearLocalStorage()
});
Then(/^I can view that the default Late Fee settings are applied$/,function() {
	addProspectActions.verifyLateFeesSettingsApplied();
	Utils.clearLocalStorage()
});
Then(/^I can view that the Customer ID is filled out$/,function() {
	addProspectActions.verifyCustomerIdFilledOut();
	Utils.clearLocalStorage()
});
Then(/^I can view a history log which contains details of the added prospect or subscriber$/,function() {
	addProspectActions.verifyLogHistory();
	Utils.clearLocalStorage()
});
Then(/^I fill the required details of prospect$/,function() {
	addProspectActions.fillProspectForm('onlyRequiredDetails');
	Utils.clearLocalStorage()
});
Then(/^I can view that the Latitude, Longitude, and Address is filled out on the map$/,function() {
	addProspectActions.verifyLatLan();
	Utils.clearLocalStorage()
});
Then(/^I can view that the Setup Date is filled out with the date the subscriber is added$/,function() {
	addProspectActions.verifyStartUpDate();
	Utils.clearLocalStorage()
});
Then(/^I can view that the Paid Thru date is filled out with the date the subscriber is added$/,function() {
	addProspectActions.verifyPaidThroughDate();
	Utils.clearLocalStorage()
});
Then(/^I can view that the default Grace Period settings are displayed in billing$/,function() {
	addProspectActions.verifyGracePeriodApply();
	Utils.clearLocalStorage()
});
Then(/^I can view that the default Auto Action settings are displayed in billing$/,function() {
	addProspectActions.verifyAutoActionSettingsApplied();
	Utils.clearLocalStorage()
});