@addProspect
Feature: Add prospect or subscriber

  Background: 
			Given I open UBO webapp
			And I login with username jcabangonautomation and password Test@1234
   
  @regression2021 @regression2021-addProspect @regression-BIL @addProspect-VPT-294 @TA-75
  Scenario: As a User, I can view the Add Prospect or Subscriber panel when I click on the Add Prospect or Subscriber menu option on the global create menu.
        When I go to add prospect interface to create a prospect
        Then I should see the Add prospect or subscriber interface

  @regression2021 @regression2021-addProspect @TA-399 @TA-449 @regression-BIL @TA-75
  Scenario: As a User, I can view the Primary Contact, Billing Contact, and Contact Emails sections in the Add Prospect or Subscriber panel.
      When I go to add prospect interface to create a prospect
      Then I should see Primary Contact, Billing Contact, and Contact Emails sections in the Add Prospect or Subscriber panel

  @regression2021 @regression2021-addProspect @regression-BIL @TA-75
  Scenario: As a User, I can click on the Add button to add the subscriber if all required fields have been field with valid values.
      When I go to add prospect interface to create a prospect
      And I fill the required details
      And I save the record
      Then I verify that the new prospect or subscriber is added in subscriber list
    
    #Fixed

  @regression2021 @regression2021-addProspect @regression-BIL @TA-828
  Scenario: As a User, I can view the newly added subscriber in the Subscriber list after adding and it's selected by default.
      When I go to add prospect interface to create a prospect
      And I fill the required details
      And I save the record
      And The newly added prospect is added successfully
      Then I verify that the new prospect or subscriber is added in subscriber list
    


  @regression2021 @regression2021-addProspect @regression-BIL @TA-75
  Scenario: As a User, I can see that Username and password are autogenerated with I select 'Account auto-generation' checkbox
      When I go to add prospect interface to create a prospect
      And I fill the required details
      And I make sure that 'Account auto-generation' option is "enabled"
      And I save the record
      Then I should see that username and password are autogenerated

    #Fixed
  @regression2021 @regression2021-addProspect @TA-450 @regression-BIL @TA-828
  Scenario: As a User, I can see that Username and password are NOT autogenerated with I uncheck 'Account auto-generation' checkbox
      When I go to add prospect interface to create a prospect
      And I fill the required details
      And I make sure that 'Account auto-generation' option is "disabled"
      And I provide username and password
      And I save the record
      Then I should see that username and password are same on username popup on subscriber details drawer


  @regression2021 @regression2021-addProspect  @regression-BIL @TA-75
  Scenario: As a User, I can view that the Subscriber dock is automatically opened for the new subscriber with accurate contact info after successfully adding the new subscriber.
      When I go to add prospect interface to create a prospect
      And I fill the required details
      And I save the record
      Then The newly added prospect is added successfully
      And The Subscriber dock is automatically opened for the new subscriber with accurate contact info


  @regression2021 @regression2021-addProspect @TA-458 @regression-BIL @TA-75
  Scenario: As a User, I can view in the Billing Status section that the default billing days settings are correctly applied to the new subscriber.
      When  I open invoicing settings from top right menu
      And  I ensure that invoice flexible billing option disabled for new subscribers
      And  I close invoicing setting to go back to billing options tab
      When I go to add prospect interface to create a prospect
      And I fill the required details
      And I save the record
      Then I can view in the Billing Status section that the default billing days settings are correctly applied to the new subscriber


  @regression2021 @regression2021-addProspect @regression-BIL @TA-75
  Scenario: As a User, I can view in the Billing Options section that the default tax setting is set correctly based on the new subscriber's billing info and the tax criteria.
      When I go to add prospect interface to create a prospect
      And I fill the required details
      And I save the record
      Then I can view in the Billing Options section that the default tax setting is set correctly based on the new subscriber's billing info and the tax criteria


  @regression2021 @regression2021-addProspect  @regression-BIL @TA-75
  Scenario: As a User, I can view that the default cycle of the new subscriber is set to "Monthly".
      When I go to add prospect interface to create a prospect
      And I fill the required details
      And I save the record
      Then I can see the default cycle of prospect as monthly


@regression2021 @regression2021-addProspect  @regression-BIL @TA-75
  Scenario: As a User, I can view that the Paper Invoice option is unchecked by default for the new subscriber.
      When I go to add prospect interface to create a prospect
      And I fill the required details
      And I save the record
      Then I can view that the Paper Invoice option is unchecked by default

    #Fixed

@regression2021 @regression2021-addProspect @regression-BIL @TA-75 @TA-828
  Scenario: As a User, I can view that the default Late Fee settings are applied to the subscriber.
      When I go to add prospect interface to create a prospect
      And I fill the required details
      And I save the record
      Then I can view that the default Late Fee settings are applied


@regression2021 @regression2021-addProspect @regression-BIL @TA-75
  Scenario: As a User, I can view that the default Grace Period settings are applied to the subscriber.
      When I ensure that default default Grace Period settings are applied in settings
      And  I go to add prospect interface to create a prospect
      And I fill the required details
      And I save the record
      Then I can view that the default Grace Period settings are displayed in billing


@regression2021 @regression2021-addProspect @regression-BIL @TA-75
  Scenario: As a User, I can view that the default Auto Action settings are applied to the subscriber.
      When I ensure default Auto Action settings are applied in settings
      And  I go to add prospect interface to create a prospect
      And I fill the required details
      And I save the record
      Then I can view that the default Auto Action settings are displayed in billing


@regression2021 @regression2021-addProspect @TA-400 @TA-451 @regression-BIL @TA-75
  Scenario: As a User, I can view that the Setup Date is filled out with the date the subscriber is added.
      When I go to add prospect interface to create a prospect
      And I fill the required details
      And I save the record
      Then I can view that the Setup Date is filled out with the date the subscriber is added

    #Fixed
@regression2021 @regression2021-addProspect @regression-BIL @TA-75 @TA-828
  Scenario: As a User, I can view that the Paid Thru date is filled out with the date the subscriber is added.
      When I go to add prospect interface to create a prospect
      And I fill the required details
      And I save the record
      Then I can view that the Paid Thru date is filled out with the date the subscriber is added


@regression2021 @regression2021-addProspect @regression-BIL @TA-75
  Scenario: As a User, I can view that the Customer ID is filled out.
      When I go to add prospect interface to create a prospect
      And I fill the required details
      And I save the record
      Then I can view that the Customer ID is filled out


@regression2021 @regression2021-addProspect @regression-BIL @TA-75
  Scenario: As a User, I can view a history log which contains details of the added prospect/subscriber.
      When I go to add prospect interface to create a prospect
      And I fill the required details
      And I save the record
      Then I can view a history log which contains details of the added prospect or subscriber

@regression2021 @regression2021-addProspect @TA-401 @TA-452 @regression-BIL @TA-75
  Scenario: As a User, I can view that the Latitude, Longitude, and Address is filled out in the map page based on the entered Primary Contact address details.
      When I go to add prospect interface to create a prospect
      Then I fill the required details of prospect
      Then I can view that the Latitude, Longitude, and Address is filled out on the map
